package com.allala.spring.service.impl;

import com.allala.spring.service.DemoService;

public class DBservice implements DemoService {

	@Override
	public long getCount() {
		// TODO Auto-generated method stub
		System.out.println("In DB fetched count of rows");
		return 20L;
	}

	@Override
	public String getDataObject() {
		System.out.println("In DB fetched Data Obj using Hiberanate");
		return "Java Onject generated by hibernate";
	}

}
